import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import 'package:qr_attendance_flut/values/strings.dart';

class HelpScreen extends StatelessWidget {
  const HelpScreen({super.key});

  @override
  Widget build(BuildContext context) {
    // TextStyle h1 = const TextStyle(fontSize: 18, fontWeight: FontWeight.bold);
    // TextStyle h2 = const TextStyle(fontSize: 16, fontWeight: FontWeight.normal);
    return Scaffold(
      appBar: AppBar(title: Text(labelHelp)),
      body: const SingleChildScrollView(
        child: Padding(padding: EdgeInsets.all(16.0), child: HtmlWidget('''
            <h2>Overview</h2>
            <p>In the QR Attendance app, QR codes play a crucial role in tracking attendance for school events and class.</p>
            <h2>Online Mode Attendance:</h2>
            <p>1. The administrator has the ability to include a participant in the attendance list by providing them with a code. Once the participant has the code, they can scan a QR Code that will be added to the shared attendance record. </p>
            <p>2. Only the account that creates the attendance event will have access to the full attendance contents, including the list of attendees who have scanned the QR code.</p>
            <p>3. Other participants will only see the QR code that they have scanned individually. This ensures privacy and prevents unauthorized access to attendance records</p>
            
            <h2>QR Codes:</h2>
            <p>The QR Codes accepted by the app are either those generated by the app itself or those that adhere to the format of <b>ID Number&Fullname&Department</b>. The QR Codes can be created in <b>Offline Mode</b>, which can be saved to phone storage.</p>
            ''')

            // Column(
            //   crossAxisAlignment: CrossAxisAlignment.start,
            //   mainAxisSize: MainAxisSize.max,
            //   mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            //   children: [
            //     Text('Overview', style: h1),
            //     Text(
            //         '\t\t\t',
            //         style: h2),
            //     Text('', style: h1),
            //     Text(
            //         '',
            //         style: h2),
            //     Text('Visibility Settings for Attendees:', style: h1),
            //     Text(
            //         '',
            //         style: h2),
            //     Text('QR Code:', style: h1),
            //   ],
            // ),
            ),
      ),
    );
  }
}
